(
 echo #################################################################
 echo # This is an envitonment file.                                  #
 echo # It was automatically generated by the setup script.           #
 echo # It is gitignored and purposely left blank.                    #
 echo # To fill its contents, please contact a project administrator. #
 echo #################################################################
 echo.
 echo. 
 echo DB_NAME=
 echo DB_PASSWORD=
 ) > .env

cd assets

bower install && npm install

grunt build

cd ..

npm install

cd ..

exit 0