#!/bin/sh

echo '
#################################################################
# This is an envitonment file.                                  #
# It was automatically generated by the setup script.           #
# It is gitignored and purposely left blank.                    #
# To fill its contents, please contact a project administrator. #
#################################################################


DB_NAME=
DB_PASSWORD=
' > .env

cd assets

bower install && npm install

grunt build

cd ..

npm install

cd ..

exit 0